FROM openjdk:17-jdk-slim as builder

COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .

RUN chmod +x ./gradlew
RUN ./gradlew dependencies

COPY src src

RUN ./gradlew bootJar

FROM openjdk:21-jdk-slim

COPY --from=builder build/libs/*.jar app.jar

EXPOSE 1000
ENTRYPOINT ["java", "-jar", "/app.jar"]
