log.path=./log
log.file.name=sollink_plus
log.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight([%level]) [%thread] [%logger] - %msg%n
log.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] [%thread] [%logger] - %msg%n