name: develop-deploy

on:
  push:
    branches:
      - develop

jobs:
  develop-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /home/techmoa/techmoa-backend  
            git checkout develop
            git pull origin develop
            docker-compose down
            docker rmi techmoa-backend_backend:latest
            docker-compose up -d --build
            docker image prune -f
          EOF