name: test

on:
  push:
    branches:
      - feature/release-test

jobs:
  create-folder:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /home/deploy/backend  
            git checkout develop
            git pull origin develop
          EOF