name: test

on:
  push:
    branches:
      - feature/release-test

jobs:
  develop-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and Pull from develop
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /home/techmoa/techmoa-backend  
            git checkout feature/release-test
            git pull origin feature/release-test
          EOF

      - name: Build and Deploy
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /home/techmoa/techmoa-backend  
            docker-compose up -d --build
            docker image prune -f
          EOF